/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

/**
 *
 * @author Sakinah
 */
public class BankFrame extends javax.swing.JFrame {

    /**
     * Creates new form BankFrame
     */
    public BankFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BankFrame = new javax.swing.JLabel();
        bsaldo = new javax.swing.JButton();
        bsetor = new javax.swing.JButton();
        btarik = new javax.swing.JButton();
        btrans = new javax.swing.JButton();
        tfsetor = new javax.swing.JTextField();
        tftarik = new javax.swing.JTextField();
        tftrans = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        bselesai = new javax.swing.JButton();
        sisasaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(202, 240, 240));
        jPanel1.setLayout(null);

        BankFrame.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BankFrame.setText("MY BANK");
        jPanel1.add(BankFrame);
        BankFrame.setBounds(290, 30, 130, 50);

        bsaldo.setText("SALDO");
        bsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaldoActionPerformed(evt);
            }
        });
        jPanel1.add(bsaldo);
        bsaldo.setBounds(60, 130, 80, 30);

        bsetor.setText("PENYETORAN");
        bsetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsetorActionPerformed(evt);
            }
        });
        jPanel1.add(bsetor);
        bsetor.setBounds(200, 130, 120, 30);

        btarik.setText("PENARIKAN");
        btarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btarikActionPerformed(evt);
            }
        });
        jPanel1.add(btarik);
        btarik.setBounds(390, 130, 100, 30);

        btrans.setText("TRANSFER");
        btrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btransActionPerformed(evt);
            }
        });
        jPanel1.add(btrans);
        btrans.setBounds(560, 130, 100, 30);
        jPanel1.add(tfsetor);
        tfsetor.setBounds(200, 180, 130, 30);
        jPanel1.add(tftarik);
        tftarik.setBounds(380, 180, 120, 30);
        jPanel1.add(tftrans);
        tftrans.setBounds(550, 180, 120, 30);
        jPanel1.add(ket);
        ket.setBounds(10, 180, 170, 30);

        bselesai.setText("SELESAI");
        bselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bselesaiActionPerformed(evt);
            }
        });
        jPanel1.add(bselesai);
        bselesai.setBounds(590, 380, 100, 30);
        jPanel1.add(sisasaldo);
        sisasaldo.setBounds(30, 220, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 430);

        setBounds(0, 0, 725, 454);
    }// </editor-fold>//GEN-END:initComponents

    private void bselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bselesaiActionPerformed
        this.dispose();
        new bankk().setVisible(true);
    }//GEN-LAST:event_bselesaiActionPerformed

    private void bsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaldoActionPerformed
        int saldo = 150000;
        ket.setText("SALDO YANG ANDA MILIKI");
        sisasaldo.setText(""+saldo);
    }//GEN-LAST:event_bsaldoActionPerformed

    private void bsetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsetorActionPerformed
        String setor = tfsetor.getText();
        String saldolast = sisasaldo.getText();
        sisasaldo.setText(""+saldolast);
        int jmlsetor = Integer.parseInt(setor);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo+jmlsetor;
        sisasaldo.setText(""+total);
    }//GEN-LAST:event_bsetorActionPerformed

    private void btarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btarikActionPerformed
        String tarikan = tftarik.getText();
            int saldo = 150000;
            int jmltarik = Integer.parseInt(tarikan);
            int total = saldo-jmltarik;
        sisasaldo.setText(""+total);
    }//GEN-LAST:event_btarikActionPerformed

    private void btransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btransActionPerformed
        String transfer = tftrans.getText();
        String saldolast = sisasaldo.getText();
        sisasaldo.setText(""+saldolast);
        int jmltransfer = Integer.parseInt(transfer);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo-jmltransfer;
        sisasaldo.setText(""+total);
    }//GEN-LAST:event_btransActionPerformed

    /**
     * @param args the command line arguments
     */
    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        new BankFrame().setVisible(true);
        this.dispose();
    }                                      
                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BankFrame;
    private javax.swing.JButton bsaldo;
    private javax.swing.JButton bselesai;
    private javax.swing.JButton bsetor;
    private javax.swing.JButton btarik;
    private javax.swing.JButton btrans;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel sisasaldo;
    private javax.swing.JTextField tfsetor;
    private javax.swing.JTextField tftarik;
    private javax.swing.JTextField tftrans;
    // End of variables declaration//GEN-END:variables
}
